### ISSUE TITLE
Issues using HTML instead of jade

### ISSUE THREAD

**Issue by kristof-mattei** [zombiQWERTY/angular-component-way-webpack-starter-kit#2]
Hi all,

First of all: thanks for this starter kit, very nice, and very well documented!

However!

I've been trying to use this project with HTML instead of JADE, and I was wondering whether you could help me out with the following: 

https://github.com/CSharpFan/angular-component-way-webpack-starter-kit/commit/4be1eaab8bb817fdb6cb4f97acb5c66bb0cb825a

With this commit, the `index.html` works fine, but the `header` fails to render. 

The error I'm getting is: 

```
HeaderComponent.js?103a*:13Uncaught TypeError: (0 , _HeaderView2.default) is not a function
```

Could you shed some light on how to properly use your code with 'the html way'. 

Thanks!

**Comment by zombiQWERTY** [comment]
Hello. Unfortunately, you can not use css modules with vanilla html. You can use ejs instead of html (http://www.embeddedjs.com). Here is ejs-loader - https://github.com/okonet/ejs-loader
